In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import datetime
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [29]:
house_3_pattern_df = pd.read_csv("house_3_30_min_resampled_patterns.csv")

In [30]:
house_3_pattern_df

    Unnamed: 0   support                                           itemsets
0            0  0.020362                  frozenset({'00:00:00 channel_2'})
1            1  0.020928                  frozenset({'00:00:00 channel_3'})
2            2  0.020362                  frozenset({'00:30:00 channel_2'})
3            3  0.020928                  frozenset({'00:30:00 channel_3'})
4            4  0.020362                  frozenset({'01:00:00 channel_2'})
..         ...       ...                                                ...
76          76  0.020362  frozenset({'21:30:00 channel_3', '21:30:00 cha...
77          77  0.020928  frozenset({'22:00:00 channel_3', '22:00:00 cha...
78          78  0.020928  frozenset({'22:30:00 channel_2', '22:30:00 cha...
79          79  0.020928  frozenset({'23:00:00 channel_3', '23:00:00 cha...
80          80  0.020928  frozenset({'23:30:00 channel_3', '23:30:00 cha...

[81 rows x 3 columns]

In [31]:
house_3_pattern_df.columns=["Number", "Support", "Itemset"]

In [32]:
house_3_pattern_df

    Number   Support                                            Itemset
0        0  0.020362                  frozenset({'00:00:00 channel_2'})
1        1  0.020928                  frozenset({'00:00:00 channel_3'})
2        2  0.020362                  frozenset({'00:30:00 channel_2'})
3        3  0.020928                  frozenset({'00:30:00 channel_3'})
4        4  0.020362                  frozenset({'01:00:00 channel_2'})
..     ...       ...                                                ...
76      76  0.020362  frozenset({'21:30:00 channel_3', '21:30:00 cha...
77      77  0.020928  frozenset({'22:00:00 channel_3', '22:00:00 cha...
78      78  0.020928  frozenset({'22:30:00 channel_2', '22:30:00 cha...
79      79  0.020928  frozenset({'23:00:00 channel_3', '23:00:00 cha...
80      80  0.020928  frozenset({'23:30:00 channel_3', '23:30:00 cha...

[81 rows x 3 columns]

In [35]:
house_3_pattern_df = house_3_pattern_df.drop(columns = ["Number"])

In [36]:
house_3_pattern_df

     Support                                            Itemset
0   0.020362                  frozenset({'00:00:00 channel_2'})
1   0.020928                  frozenset({'00:00:00 channel_3'})
2   0.020362                  frozenset({'00:30:00 channel_2'})
3   0.020928                  frozenset({'00:30:00 channel_3'})
4   0.020362                  frozenset({'01:00:00 channel_2'})
..       ...                                                ...
76  0.020362  frozenset({'21:30:00 channel_3', '21:30:00 cha...
77  0.020928  frozenset({'22:00:00 channel_3', '22:00:00 cha...
78  0.020928  frozenset({'22:30:00 channel_2', '22:30:00 cha...
79  0.020928  frozenset({'23:00:00 channel_3', '23:00:00 cha...
80  0.020928  frozenset({'23:30:00 channel_3', '23:30:00 cha...

[81 rows x 2 columns]

In [45]:
timestamp = set()
for item in house_3_pattern_df.Itemset:
    timestamp.add(item.split("'")[1].split(" ")[0])

In [48]:
timestamp

{'00:00:00',
 '00:30:00',
 '01:00:00',
 '01:30:00',
 '02:00:00',
 '02:30:00',
 '03:00:00',
 '03:30:00',
 '04:00:00',
 '04:30:00',
 '05:00:00',
 '05:30:00',
 '06:00:00',
 '06:30:00',
 '07:00:00',
 '07:30:00',
 '08:00:00',
 '08:30:00',
 '10:30:00',
 '11:00:00',
 '11:30:00',
 '12:00:00',
 '12:30:00',
 '13:00:00',
 '13:30:00',
 '14:00:00',
 '14:30:00',
 '15:00:00',
 '15:30:00',
 '16:00:00',
 '16:30:00',
 '17:00:00',
 '17:30:00',
 '18:00:00',
 '18:30:00',
 '19:00:00',
 '19:30:00',
 '20:00:00',
 '20:30:00',
 '21:00:00',
 '21:30:00',
 '22:00:00',
 '22:30:00',
 '23:00:00',
 '23:30:00'}

In [49]:
# have a list of 48 timestamps and check for each timestamps how many records are there in the dataframe

In [63]:
datetime.datetime.now()

datetime.datetime(2020, 4, 16, 21, 36, 20, 267382)

In [64]:
house_2_patterns = pd.read_csv("house_2_30_min_resampled_patterns_2.csv")

In [66]:
house_2_patterns.columns=["Number", "Support", "Itemset"]

In [67]:
house_2_patterns = house_2_patterns.drop(columns = ["Number"])

In [108]:
house_2_patterns

       Support                                            Itemset
0     0.015519                 frozenset({'00:00:00 channel_10'})
1     0.020831                  frozenset({'00:00:00 channel_4'})
2     0.020831                  frozenset({'00:00:00 channel_5'})
3     0.020831                  frozenset({'00:00:00 channel_6'})
4     0.015519                  frozenset({'00:00:00 channel_8'})
...        ...                                                ...
9739  0.012603  frozenset({'08:00:00 channel_10', '08:00:00 ch...
9740  0.012603  frozenset({'08:30:00 channel_9', '08:30:00 cha...
9741  0.012603  frozenset({'17:00:00 channel_6', '17:00:00 cha...
9742  0.012603  frozenset({'17:30:00 channel_5', '17:30:00 cha...
9743  0.012603  frozenset({'21:30:00 channel_4', '21:30:00 cha...

[9744 rows x 2 columns]

In [112]:
house_2_patterns.sort_values(by=['Support'], ascending=False)[200:250]

       Support                                            Itemset
521   0.020831  frozenset({'05:00:00 channel_5', '05:00:00 cha...
532   0.020831  frozenset({'05:30:00 channel_4', '05:30:00 cha...
533   0.020831  frozenset({'05:30:00 channel_4', '05:30:00 cha...
536   0.020831  frozenset({'05:30:00 channel_6', '05:30:00 cha...
547   0.020831  frozenset({'06:00:00 channel_5', '06:00:00 cha...
548   0.020831  frozenset({'06:00:00 channel_6', '06:00:00 cha...
551   0.020831  frozenset({'06:00:00 channel_6', '06:00:00 cha...
1441  0.020831  frozenset({'23:30:00 channel_5', '23:30:00 cha...
2248  0.020831  frozenset({'10:30:00 channel_5', '10:30:00 cha...
1430  0.020831  frozenset({'23:00:00 channel_5', '23:00:00 cha...
1427  0.020831  frozenset({'23:00:00 channel_4', '23:00:00 cha...
1426  0.020831  frozenset({'23:00:00 channel_4', '23:00:00 cha...
1415  0.020831  frozenset({'22:30:00 channel_6', '22:30:00 cha...
1412  0.020831  frozenset({'22:30:00 channel_4', '22:30:00 cha...
1411  0.020831  frozenset({'22:30:00 channel_4', '22:30:00 cha...
1261  0.020831  frozenset({'20:00:00 channel_6', '20:00:00 cha...
3270  0.020831  frozenset({'23:00:00 channel_4', '23:00:00 cha...
811   0.020831  frozenset({'10:30:00 channel_5', '10:30:00 cha...
217   0.020831                  frozenset({'15:30:00 channel_4'})
45    0.020831                  frozenset({'03:30:00 channel_6'})
33    0.020831                  frozenset({'02:30:00 channel_6'})
128   0.020831                  frozenset({'09:00:00 channel_5'})
127   0.020831                  frozenset({'09:00:00 channel_4'})
37    0.020831                  frozenset({'03:00:00 channel_4'})
38    0.020831                  frozenset({'03:00:00 channel_5'})
39    0.020831                  frozenset({'03:00:00 channel_6'})
43    0.020831                  frozenset({'03:30:00 channel_4'})
44    0.020831                  frozenset({'03:30:00 channel_5'})
49    0.020831                  frozenset({'04:00:00 channel_4'})
63    0.020831                  frozenset({'05:00:00 channel_6'})
50    0.020831                  frozenset({'04:00:00 channel_5'})
51    0.020831                  frozenset({'04:00:00 channel_6'})
55    0.020831                  frozenset({'04:30:00 channel_4'})
9     0.020831                  frozenset({'00:30:00 channel_6'})
8     0.020831                  frozenset({'00:30:00 channel_5'})
57    0.020831                  frozenset({'04:30:00 channel_6'})
7     0.020831                  frozenset({'00:30:00 channel_4'})
61    0.020831                  frozenset({'05:00:00 channel_4'})
13    0.020831                  frozenset({'01:00:00 channel_4'})
32    0.020831                  frozenset({'02:30:00 channel_5'})
31    0.020831                  frozenset({'02:30:00 channel_4'})
129   0.020831                  frozenset({'09:00:00 channel_6'})
19    0.020831                  frozenset({'01:30:00 channel_4'})
149   0.020831                  frozenset({'10:30:00 channel_6'})
148   0.020831                  frozenset({'10:30:00 channel_5'})
147   0.020831                  frozenset({'10:30:00 channel_4'})
15    0.020831                  frozenset({'01:00:00 channel_6'})
20    0.020831                  frozenset({'01:30:00 channel_5'})
21    0.020831                  frozenset({'01:30:00 channel_6'})
142   0.020831                  frozenset({'10:00:00 channel_6'})

In [71]:
channels = set()
for item in house_2_patterns.Itemset:
    channels.add(item.split("'")[1].split(" ")[1])

In [98]:
channels

{'channel_10',
 'channel_12',
 'channel_13',
 'channel_14',
 'channel_17',
 'channel_18',
 'channel_2',
 'channel_3',
 'channel_4',
 'channel_5',
 'channel_6',
 'channel_8',
 'channel_9'}

In [118]:
timestamp = set()
for item in house_2_patterns.Itemset:
    timestamp.add(item.split("'")[1].split(" ")[0])

In [119]:
len(timestamp)

48

In [125]:
house_2_patterns.Itemset[521]

"frozenset({'05:00:00 channel_5', '05:00:00 channel_6'})"

In [126]:
house_2_patterns.Itemset[521].split(",")[1].split("'")[1].split(" ")[1]

'channel_6'

In [ ]:
time_appliance_dict = dict()
list_of_patterns = []
pattern_support_tuple = []

for

In [82]:
channel_2 = np.load("./Channel_On_Off_data/House_2/" + "channel_2.npy", allow_pickle=True)

In [88]:
channel_2[-100:]

array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '2013-10-08 21:30:00', '2013-10-08 22:00:00',
       '2013-10-08 22:30:00', '2013-10-08 23:00:00', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '2013-10-09 19:00:00',
       '2013-10-09 19:30:00', '2013-10-09 20:00:00',
       '2013-10-09 20:30:00', '2013-10-09 21:00:00',
       '2013-10-09 21:30:00', '2013-10-09 22:00:00', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'], dtype='<U19')

In [109]:
[7,11,15,16,19]

[7, 11, 15, 16, 19]